export const GLIMPSE_BASE_URL = "glimpse";

export interface GlimpseInterface {
  id: string;
  bunny_video_id: string;
  thumbnail_url: string;
  duration_seconds: number;
  title: string | null;
  description: string | null;
  author_profile_id: string;
  author_display_name: string;
  author_avatar_url: string;
  likes_count: number;
  views_count: number;
  saves_count: number;
  is_featured: boolean;
  is_recommended: boolean;
  published_at: Date | string | number;
  tags: string[];
}

export interface GlimpsePaginationMeta {
  totalCount: number;
  currentPage: number;
  pageSize: number;
  hasNextPage: boolean;
}

export interface GlimpseResponseInterface {
  data: GlimpseInterface[];
  meta: GlimpsePaginationMeta;
}

// Dummy data with placeholder images
export const dummyGlimpses: GlimpseResponseInterface = {
  data: [
    {
      id: "story-001-burnout",
      bunny_video_id: "video_burnout_001",
      thumbnail_url: "https://picsum.photos/seed/burnout/400/600",
      duration_seconds: 58,
      title: "How I Overcame Burnout as a Software Engineer",
      description:
        "My journey from complete exhaustion to finding balance in tech",
      author_profile_id: "user_story_001",
      author_display_name: "David Chen",
      author_avatar_url: "https://picsum.photos/seed/davidchen/100/100",
      likes_count: 8400,
      views_count: 142000,
      saves_count: 5200,
      is_featured: true,
      is_recommended: true,
      published_at: "2026-01-13T09:30:00Z",
      tags: [
        "burnout",
        "mental-health",
        "tech-industry",
        "recovery",
        "work-life-balance",
      ],
    },
    {
      id: "story-002-anxiety",
      bunny_video_id: "video_anxiety_002",
      thumbnail_url: "https://picsum.photos/seed/anxiety/400/600",
      duration_seconds: 45,
      title: "Living with Anxiety: My Daily Reality",
      description: "What it's really like to have generalized anxiety disorder",
      author_profile_id: "user_story_002",
      author_display_name: "Maya Rodriguez",
      author_avatar_url: "https://picsum.photos/seed/mayar/100/100",
      likes_count: 12500,
      views_count: 218000,
      saves_count: 9800,
      is_featured: true,
      is_recommended: true,
      published_at: "2026-01-12T14:20:00Z",
      tags: ["anxiety", "mental-health", "personal-story", "awareness", "gad"],
    },
    {
      id: "story-003-therapist",
      bunny_video_id: "video_therapist_003",
      thumbnail_url: "https://picsum.photos/seed/therapist/400/600",
      duration_seconds: 52,
      title: "Why I Started Therapy (and Why You Should Too)",
      description:
        "Breaking the stigma: A therapist shares their own therapy journey",
      author_profile_id: "user_story_003",
      author_display_name: "Dr. James Williams, LMFT",
      author_avatar_url: "https://picsum.photos/seed/drjames/100/100",
      likes_count: 15200,
      views_count: 267000,
      saves_count: 11400,
      is_featured: true,
      is_recommended: true,
      published_at: "2026-01-11T11:00:00Z",
      tags: ["therapy", "mental-health", "stigma", "professional", "healing"],
    },
    {
      id: "story-004-postpartum",
      bunny_video_id: "video_postpartum_004",
      thumbnail_url: "https://picsum.photos/seed/postpartum/400/600",
      duration_seconds: 60,
      title: "My Postpartum Depression Story",
      description: "The struggle nobody talks about after having a baby",
      author_profile_id: "user_story_004",
      author_display_name: "Sarah Mitchell",
      author_avatar_url: "https://picsum.photos/seed/sarahm/100/100",
      likes_count: 18700,
      views_count: 324000,
      saves_count: 14200,
      is_featured: true,
      is_recommended: true,
      published_at: "2026-01-10T16:45:00Z",
      tags: [
        "postpartum",
        "depression",
        "motherhood",
        "mental-health",
        "support",
      ],
    },
    {
      id: "story-005-ptsd",
      bunny_video_id: "video_ptsd_005",
      thumbnail_url: "https://picsum.photos/seed/veteran/400/600",
      duration_seconds: 55,
      title: "Veteran Shares PTSD Recovery Journey",
      description: "From Afghanistan to healing: One veteran's story of hope",
      author_profile_id: "user_story_005",
      author_display_name: "Michael Thompson",
      author_avatar_url: "https://picsum.photos/seed/michael/100/100",
      likes_count: 9800,
      views_count: 176000,
      saves_count: 6700,
      is_featured: true,
      is_recommended: true,
      published_at: "2026-01-09T10:15:00Z",
      tags: ["ptsd", "veteran", "recovery", "mental-health", "trauma"],
    },
    {
      id: "story-006-student",
      bunny_video_id: "video_student_006",
      thumbnail_url: "https://picsum.photos/seed/student/400/600",
      duration_seconds: 42,
      title: "College Student Opens Up About Depression",
      description: "How I balanced mental health and academic pressure",
      author_profile_id: "user_story_006",
      author_display_name: "Emma Johnson",
      author_avatar_url: "https://picsum.photos/seed/emmaj/100/100",
      likes_count: 11300,
      views_count: 198000,
      saves_count: 8900,
      is_featured: false,
      is_recommended: true,
      published_at: "2026-01-08T13:30:00Z",
      tags: [
        "depression",
        "college",
        "student-life",
        "mental-health",
        "academic-stress",
      ],
    },
    {
      id: "story-007-bipolar",
      bunny_video_id: "video_bipolar_007",
      thumbnail_url: "https://picsum.photos/seed/bipolar/400/600",
      duration_seconds: 59,
      title: "Life with Bipolar Disorder: My Truth",
      description: "Managing highs and lows - a personal account",
      author_profile_id: "user_story_007",
      author_display_name: "Marcus Lee",
      author_avatar_url: "https://picsum.photos/seed/marcusl/100/100",
      likes_count: 7600,
      views_count: 134000,
      saves_count: 5400,
      is_featured: false,
      is_recommended: true,
      published_at: "2026-01-07T09:00:00Z",
      tags: [
        "bipolar-disorder",
        "mental-health",
        "personal-story",
        "awareness",
        "medication",
      ],
    },
    {
      id: "story-008-grief",
      bunny_video_id: "video_grief_008",
      thumbnail_url: "https://picsum.photos/seed/grief/400/600",
      duration_seconds: 48,
      title: "Navigating Grief After Losing My Sister",
      description: "How I learned to live with loss and find joy again",
      author_profile_id: "user_story_008",
      author_display_name: "Aisha Patel",
      author_avatar_url: "https://picsum.photos/seed/aisha/100/100",
      likes_count: 14800,
      views_count: 256000,
      saves_count: 12100,
      is_featured: true,
      is_recommended: true,
      published_at: "2026-01-06T15:20:00Z",
      tags: ["grief", "loss", "mental-health", "healing", "family"],
    },
    {
      id: "story-009-psychiatrist",
      bunny_video_id: "video_psych_009",
      thumbnail_url: "https://picsum.photos/seed/psychiatrist/400/600",
      duration_seconds: 54,
      title: "Psychiatrist: What I Wish Patients Knew",
      description:
        "Breaking down mental health myths from a medical perspective",
      author_profile_id: "user_story_009",
      author_display_name: "Dr. Lisa Anderson, MD",
      author_avatar_url: "https://picsum.photos/seed/drlisa/100/100",
      likes_count: 13400,
      views_count: 234000,
      saves_count: 10200,
      is_featured: true,
      is_recommended: true,
      published_at: "2026-01-05T11:45:00Z",
      tags: [
        "psychiatry",
        "mental-health",
        "professional",
        "education",
        "medication",
      ],
    },
    {
      id: "story-010-panic",
      bunny_video_id: "video_panic_010",
      thumbnail_url: "https://picsum.photos/seed/panic/400/600",
      duration_seconds: 41,
      title: "My First Panic Attack Changed Everything",
      description: "The moment I realized I needed help with my mental health",
      author_profile_id: "user_story_010",
      author_display_name: "Tyler Brooks",
      author_avatar_url: "https://picsum.photos/seed/tyler/100/100",
      likes_count: 9200,
      views_count: 167000,
      saves_count: 7300,
      is_featured: false,
      is_recommended: true,
      published_at: "2026-01-04T08:30:00Z",
      tags: [
        "panic-attack",
        "anxiety",
        "mental-health",
        "personal-story",
        "help",
      ],
    },
    {
      id: "story-011-workplace",
      bunny_video_id: "video_workplace_011",
      thumbnail_url: "https://picsum.photos/seed/workplace/400/600",
      duration_seconds: 50,
      title: "Speaking Up About Mental Health at Work",
      description: "How I told my boss about my depression",
      author_profile_id: "user_story_011",
      author_display_name: "Priya Sharma",
      author_avatar_url: "https://picsum.photos/seed/priya/100/100",
      likes_count: 10600,
      views_count: 189000,
      saves_count: 8100,
      is_featured: false,
      is_recommended: true,
      published_at: "2026-01-03T12:00:00Z",
      tags: [
        "workplace",
        "mental-health",
        "advocacy",
        "depression",
        "corporate",
      ],
    },
    {
      id: "story-012-recovery",
      bunny_video_id: "video_recovery_012",
      thumbnail_url: "https://picsum.photos/seed/recovery/400/600",
      duration_seconds: 57,
      title: "5 Years in Recovery: What I've Learned",
      description: "My journey from suicidal thoughts to thriving",
      author_profile_id: "user_story_012",
      author_display_name: "Jordan Martinez",
      author_avatar_url: "https://picsum.photos/seed/jordanm/100/100",
      likes_count: 21300,
      views_count: 387000,
      saves_count: 17800,
      is_featured: true,
      is_recommended: true,
      published_at: "2026-01-02T17:00:00Z",
      tags: [
        "recovery",
        "mental-health",
        "suicide-prevention",
        "hope",
        "healing",
      ],
    },
    {
      id: "story-013-teen",
      bunny_video_id: "video_teen_013",
      thumbnail_url: "https://picsum.photos/seed/teenager/400/600",
      duration_seconds: 44,
      title: "Teen's Honest Take on Social Media & Mental Health",
      description:
        "How Instagram affected my self-esteem and what I did about it",
      author_profile_id: "user_story_013",
      author_display_name: "Zoe Taylor",
      author_avatar_url: "https://picsum.photos/seed/zoe/100/100",
      likes_count: 16700,
      views_count: 298000,
      saves_count: 13200,
      is_featured: true,
      is_recommended: true,
      published_at: "2026-01-01T14:15:00Z",
      tags: ["teen", "social-media", "mental-health", "self-esteem", "youth"],
    },
    {
      id: "story-014-caregiver",
      bunny_video_id: "video_caregiver_014",
      thumbnail_url: "https://picsum.photos/seed/caregiver/400/600",
      duration_seconds: 53,
      title: "Caring for a Partner with Mental Illness",
      description:
        "What it's like to support someone you love through depression",
      author_profile_id: "user_story_014",
      author_display_name: "Robert Kim",
      author_avatar_url: "https://picsum.photos/seed/robertk/100/100",
      likes_count: 8900,
      views_count: 154000,
      saves_count: 6800,
      is_featured: false,
      is_recommended: true,
      published_at: "2025-12-31T10:30:00Z",
      tags: [
        "caregiver",
        "support",
        "mental-health",
        "relationships",
        "depression",
      ],
    },
    {
      id: "story-015-adhd",
      bunny_video_id: "video_adhd_015",
      thumbnail_url: "https://picsum.photos/seed/adhd/400/600",
      duration_seconds: 46,
      title: "Diagnosed with ADHD at 28: My Story",
      description: "Finally understanding why I've always felt different",
      author_profile_id: "user_story_015",
      author_display_name: "Sophie Anderson",
      author_avatar_url: "https://picsum.photos/seed/sophiea/100/100",
      likes_count: 19400,
      views_count: 342000,
      saves_count: 15600,
      is_featured: true,
      is_recommended: true,
      published_at: "2025-12-30T16:00:00Z",
      tags: [
        "adhd",
        "diagnosis",
        "mental-health",
        "neurodivergent",
        "late-diagnosis",
      ],
    },
    {
      id: "story-016-counselor",
      bunny_video_id: "video_counselor_016",
      thumbnail_url: "https://picsum.photos/seed/counselor/400/600",
      duration_seconds: 51,
      title: "School Counselor: The Mental Health Crisis I See",
      description: "What's really happening with teen mental health today",
      author_profile_id: "user_story_016",
      author_display_name: "Ms. Rachel Green, LPC",
      author_avatar_url: "https://picsum.photos/seed/rachelg/100/100",
      likes_count: 11800,
      views_count: 206000,
      saves_count: 9400,
      is_featured: true,
      is_recommended: true,
      published_at: "2025-12-29T09:45:00Z",
      tags: [
        "counselor",
        "teen-mental-health",
        "professional",
        "school",
        "crisis",
      ],
    },
  ],
  meta: {
    totalCount: 156,
    currentPage: 1,
    pageSize: 16,
    hasNextPage: true,
  },
};
