create schema if not exists "private";

create type "public"."campfire_member_status" as enum ('pending', 'approved', 'rejected');

create type "public"."campfire_role" as enum ('camper', 'firekeeper', 'firestarter');

create type "public"."campfire_visibility" as enum ('public', 'private');

create type "public"."interaction_style_enum" as enum ('support', 'discussion', 'guided', 'creative');

create type "public"."loading_experience_types" as enum ('none', 'breathing', 'affirmation');

create type "public"."sensitive_content_mode" as enum ('show', 'blur', 'hide');

create type "public"."theme_options" as enum ('system', 'light', 'dark');


  create table "private"."profile_private" (
    "user_id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "email" text,
    "consent_version" integer not null default 0,
    "has_consented" boolean not null default false,
    "account_state" text not null default 'active'::text,
    "restricted_reason" text,
    "restricted_until" timestamp with time zone,
    "location_country_code" text,
    "location_region" text,
    "location_city" text
      );


alter table "private"."profile_private" enable row level security;


  create table "public"."campfire_guide_resources" (
    "id" bigint generated by default as identity not null,
    "campfire_id" uuid not null,
    "label" text not null,
    "url" text,
    "sort_order" integer not null default 0,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."campfire_guide_resources" enable row level security;


  create table "public"."campfire_lanes" (
    "id" uuid not null default gen_random_uuid(),
    "realm_id" uuid not null,
    "key" text not null,
    "name" text not null,
    "description" text,
    "sort_order" integer not null default 0,
    "is_active" boolean not null default true,
    "created_at" timestamp with time zone not null default now(),
    "is_high_safety" boolean default false
      );


alter table "public"."campfire_lanes" enable row level security;


  create table "public"."campfire_members" (
    "campfire_id" uuid not null,
    "user_id" uuid not null,
    "role" public.campfire_role not null default 'camper'::public.campfire_role,
    "status" public.campfire_member_status not null default 'approved'::public.campfire_member_status,
    "joined_at" timestamp with time zone not null default now(),
    "is_favorite" boolean not null default false
      );


alter table "public"."campfire_members" enable row level security;


  create table "public"."campfire_realms" (
    "id" uuid not null default gen_random_uuid(),
    "key" text not null,
    "name" text not null,
    "description" text,
    "sort_order" integer not null default 0,
    "is_active" boolean not null default true,
    "created_at" timestamp with time zone not null default now(),
    "is_high_safety" boolean default false
      );


alter table "public"."campfire_realms" enable row level security;


  create table "public"."campfire_settings" (
    "campfire_id" uuid not null,
    "guide_enabled" boolean not null default true,
    "guide_header_image" text default 'Banner'::text,
    "guide_header_layout" text default 'Avatar and name'::text,
    "guide_show_on_join" boolean not null default false,
    "guide_welcome_message" text not null default 'Welcome to our campfire, {username}!'::text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."campfire_settings" enable row level security;


  create table "public"."campfires" (
    "id" uuid not null default gen_random_uuid(),
    "created_by" uuid not null,
    "name" text not null,
    "slug" text not null,
    "description" text,
    "icon_path" text,
    "banner_path" text,
    "realm_id" uuid not null,
    "lane_id" uuid,
    "interaction_style" public.interaction_style_enum not null default 'discussion'::public.interaction_style_enum,
    "visibility" public.campfire_visibility not null default 'public'::public.campfire_visibility,
    "member_count" integer not null default 0,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."campfires" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "username" text,
    "avatar_url" text default 'default_profile.png'::text,
    "is_anonymous" boolean not null default false,
    "is_verified_badge" boolean not null default false,
    "reputation_score" bigint not null default 0,
    "theme" text,
    "config" text
      );


alter table "public"."profiles" enable row level security;


  create table "public"."user_preferences" (
    "user_id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "theme" public.theme_options not null default 'system'::public.theme_options,
    "preferred_language" text not null default 'en'::text,
    "sensitive_content_mode" public.sensitive_content_mode not null default 'show'::public.sensitive_content_mode,
    "mark_sensitive_by_default" boolean not null default false,
    "guided_tour_enabled" boolean not null default true,
    "auto_save_drafts" boolean not null default false,
    "daily_prompt_enabled" boolean not null default true,
    "allow_anonymous_replies" boolean not null default false,
    "loading_experience" public.loading_experience_types not null default 'none'::public.loading_experience_types,
    "notifications_enabled" boolean not null default true,
    "push_enabled" boolean not null default true
      );


alter table "public"."user_preferences" enable row level security;

CREATE INDEX profile_private_location_country_idx ON private.profile_private USING btree (location_country_code);

CREATE INDEX profile_private_location_region_idx ON private.profile_private USING btree (location_region);

CREATE UNIQUE INDEX profile_private_pkey ON private.profile_private USING btree (user_id);

CREATE UNIQUE INDEX campfire_guide_resources_pkey ON public.campfire_guide_resources USING btree (id);

CREATE UNIQUE INDEX campfire_lanes_pkey ON public.campfire_lanes USING btree (id);

CREATE UNIQUE INDEX campfire_members_pkey ON public.campfire_members USING btree (campfire_id, user_id);

CREATE UNIQUE INDEX campfire_realms_pkey ON public.campfire_realms USING btree (id);

CREATE UNIQUE INDEX campfire_scopes_key_unique ON public.campfire_realms USING btree (key);

CREATE UNIQUE INDEX campfire_settings_pkey ON public.campfire_settings USING btree (campfire_id);

CREATE UNIQUE INDEX campfire_topics_realm_key_unique ON public.campfire_lanes USING btree (realm_id, key);

CREATE UNIQUE INDEX campfires_pkey ON public.campfires USING btree (id);

CREATE UNIQUE INDEX campfires_slug_key ON public.campfires USING btree (slug);

CREATE INDEX idx_campfire_guide_resources_campfire ON public.campfire_guide_resources USING btree (campfire_id, sort_order);

CREATE INDEX idx_campfire_members_campfire_id ON public.campfire_members USING btree (campfire_id);

CREATE INDEX idx_campfire_members_campfire_status ON public.campfire_members USING btree (campfire_id, status);

CREATE INDEX idx_campfire_members_user_favorite ON public.campfire_members USING btree (user_id, campfire_id) WHERE (is_favorite = true);

CREATE INDEX idx_campfire_members_user_id ON public.campfire_members USING btree (user_id);

CREATE INDEX idx_campfire_topics_realm_id ON public.campfire_lanes USING btree (realm_id);

CREATE INDEX idx_campfires_created_by ON public.campfires USING btree (created_by);

CREATE INDEX idx_campfires_lane ON public.campfires USING btree (lane_id);

CREATE INDEX idx_campfires_purpose ON public.campfires USING btree (interaction_style);

CREATE INDEX idx_campfires_realm ON public.campfires USING btree (realm_id);

CREATE INDEX idx_campfires_slug ON public.campfires USING btree (slug);

CREATE INDEX idx_campfires_visibility ON public.campfires USING btree (visibility);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX profiles_username_ci_unique ON public.profiles USING btree (lower(username)) WHERE (username IS NOT NULL);

CREATE UNIQUE INDEX user_preferences_pkey ON public.user_preferences USING btree (user_id);

alter table "private"."profile_private" add constraint "profile_private_pkey" PRIMARY KEY using index "profile_private_pkey";

alter table "public"."campfire_guide_resources" add constraint "campfire_guide_resources_pkey" PRIMARY KEY using index "campfire_guide_resources_pkey";

alter table "public"."campfire_lanes" add constraint "campfire_lanes_pkey" PRIMARY KEY using index "campfire_lanes_pkey";

alter table "public"."campfire_members" add constraint "campfire_members_pkey" PRIMARY KEY using index "campfire_members_pkey";

alter table "public"."campfire_realms" add constraint "campfire_realms_pkey" PRIMARY KEY using index "campfire_realms_pkey";

alter table "public"."campfire_settings" add constraint "campfire_settings_pkey" PRIMARY KEY using index "campfire_settings_pkey";

alter table "public"."campfires" add constraint "campfires_pkey" PRIMARY KEY using index "campfires_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."user_preferences" add constraint "user_preferences_pkey" PRIMARY KEY using index "user_preferences_pkey";

alter table "private"."profile_private" add constraint "profile_private_city_len" CHECK (((location_city IS NULL) OR (length(location_city) <= 100))) not valid;

alter table "private"."profile_private" validate constraint "profile_private_city_len";

alter table "private"."profile_private" add constraint "profile_private_country_code_len" CHECK (((location_country_code IS NULL) OR (length(location_country_code) = 2))) not valid;

alter table "private"."profile_private" validate constraint "profile_private_country_code_len";

alter table "private"."profile_private" add constraint "profile_private_region_len" CHECK (((location_region IS NULL) OR (length(location_region) <= 100))) not valid;

alter table "private"."profile_private" validate constraint "profile_private_region_len";

alter table "private"."profile_private" add constraint "profile_private_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "private"."profile_private" validate constraint "profile_private_user_id_fkey";

alter table "public"."campfire_guide_resources" add constraint "campfire_guide_resources_campfire_id_fkey" FOREIGN KEY (campfire_id) REFERENCES public.campfires(id) ON DELETE CASCADE not valid;

alter table "public"."campfire_guide_resources" validate constraint "campfire_guide_resources_campfire_id_fkey";

alter table "public"."campfire_guide_resources" add constraint "cgr_label_len" CHECK (((char_length(label) >= 1) AND (char_length(label) <= 100))) not valid;

alter table "public"."campfire_guide_resources" validate constraint "cgr_label_len";

alter table "public"."campfire_guide_resources" add constraint "cgr_url_len" CHECK (((url IS NULL) OR (char_length(url) <= 2048))) not valid;

alter table "public"."campfire_guide_resources" validate constraint "cgr_url_len";

alter table "public"."campfire_lanes" add constraint "campfire_lanes_realm_id_fkey" FOREIGN KEY (realm_id) REFERENCES public.campfire_realms(id) ON DELETE CASCADE not valid;

alter table "public"."campfire_lanes" validate constraint "campfire_lanes_realm_id_fkey";

alter table "public"."campfire_lanes" add constraint "campfire_topics_key_format" CHECK ((key ~ '^[a-z_]+$'::text)) not valid;

alter table "public"."campfire_lanes" validate constraint "campfire_topics_key_format";

alter table "public"."campfire_lanes" add constraint "campfire_topics_realm_key_unique" UNIQUE using index "campfire_topics_realm_key_unique";

alter table "public"."campfire_members" add constraint "campfire_members_campfire_id_fkey" FOREIGN KEY (campfire_id) REFERENCES public.campfires(id) ON DELETE CASCADE not valid;

alter table "public"."campfire_members" validate constraint "campfire_members_campfire_id_fkey";

alter table "public"."campfire_members" add constraint "campfire_members_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."campfire_members" validate constraint "campfire_members_user_id_fkey";

alter table "public"."campfire_realms" add constraint "campfire_scopes_key_format" CHECK ((key ~ '^[a-z_]+$'::text)) not valid;

alter table "public"."campfire_realms" validate constraint "campfire_scopes_key_format";

alter table "public"."campfire_realms" add constraint "campfire_scopes_key_unique" UNIQUE using index "campfire_scopes_key_unique";

alter table "public"."campfire_settings" add constraint "campfire_settings_campfire_id_fkey" FOREIGN KEY (campfire_id) REFERENCES public.campfires(id) ON DELETE CASCADE not valid;

alter table "public"."campfire_settings" validate constraint "campfire_settings_campfire_id_fkey";

alter table "public"."campfire_settings" add constraint "campfire_settings_welcome_len" CHECK ((char_length(guide_welcome_message) <= 500)) not valid;

alter table "public"."campfire_settings" validate constraint "campfire_settings_welcome_len";

alter table "public"."campfires" add constraint "campfires_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."campfires" validate constraint "campfires_created_by_fkey";

alter table "public"."campfires" add constraint "campfires_lane_id_fkey" FOREIGN KEY (lane_id) REFERENCES public.campfire_lanes(id) not valid;

alter table "public"."campfires" validate constraint "campfires_lane_id_fkey";

alter table "public"."campfires" add constraint "campfires_name_len" CHECK (((char_length(name) >= 3) AND (char_length(name) <= 50))) not valid;

alter table "public"."campfires" validate constraint "campfires_name_len";

alter table "public"."campfires" add constraint "campfires_realm_id_fkey" FOREIGN KEY (realm_id) REFERENCES public.campfire_realms(id) not valid;

alter table "public"."campfires" validate constraint "campfires_realm_id_fkey";

alter table "public"."campfires" add constraint "campfires_slug_format" CHECK ((slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'::text)) not valid;

alter table "public"."campfires" validate constraint "campfires_slug_format";

alter table "public"."campfires" add constraint "campfires_slug_key" UNIQUE using index "campfires_slug_key";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."profiles" add constraint "profiles_username_format" CHECK (((username IS NULL) OR (username ~ '^[a-zA-Z0-9_-]{3,30}$'::text))) not valid;

alter table "public"."profiles" validate constraint "profiles_username_format";

alter table "public"."profiles" add constraint "profiles_username_len" CHECK (((username IS NULL) OR ((length(username) >= 3) AND (length(username) <= 30)))) not valid;

alter table "public"."profiles" validate constraint "profiles_username_len";

alter table "public"."user_preferences" add constraint "user_preferences_lang_len" CHECK (((length(preferred_language) >= 2) AND (length(preferred_language) <= 10))) not valid;

alter table "public"."user_preferences" validate constraint "user_preferences_lang_len";

alter table "public"."user_preferences" add constraint "user_preferences_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."user_preferences" validate constraint "user_preferences_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION private.provision_user_on_auth_insert()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_username text;
  v_is_anonymous boolean;
begin
  -- username may be provided at signup; if not present, keep null
  v_username := nullif(new.raw_user_meta_data->>'username', '');

  -- infer anonymous sign-in from auth metadata (avoid relying on nonstandard columns)
  -- note: this is a best-effort inference and remains a display/state flag only.
  v_is_anonymous :=
    coalesce((new.is_anonymous) = 'true', false);

  -- public profile card
  insert into public.profiles (
    id,
    username,
    avatar_url,
    is_anonymous
  )
  values (
    new.id,
    v_username,
    'default_profile.png',
    v_is_anonymous
  )
  on conflict (id) do nothing;

  -- sensitive private row (minimal defaults; email optional)
  insert into private.profile_private (
    user_id,
    email
  )
  values (
    new.id,
    nullif(new.email, '')
  )
  on conflict (user_id) do nothing;

  -- preferences row (defaults)
  insert into public.user_preferences (
    user_id
  )
  values (
    new.id
  )
  on conflict (user_id) do nothing;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION private.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  new.updated_at := now();
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.ensure_campfire_settings()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.campfire_settings (campfire_id)
  values (new.id)
  on conflict (campfire_id) do nothing;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.recount_campfire_members(p_campfire_id uuid)
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
  update public.campfires c
  set member_count = (
    select count(*)
    from public.campfire_members m
    where m.campfire_id = c.id
      and m.status = 'approved'
  ),
  updated_at = now()
  where c.id = p_campfire_id;
$function$
;

CREATE OR REPLACE FUNCTION public.tr_campfire_members_recount()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_campfire_id uuid;
begin
  v_campfire_id := coalesce(new.campfire_id, old.campfire_id);

  -- only recompute when insert/delete, or when status changes
  if (tg_op = 'UPDATE') then
    if new.status is not distinct from old.status then
      return new;
    end if;
  end if;

  perform public.recount_campfire_members(v_campfire_id);
  return coalesce(new, old);
end;
$function$
;

grant delete on table "private"."profile_private" to "service_role";

grant insert on table "private"."profile_private" to "service_role";

grant select on table "private"."profile_private" to "service_role";

grant update on table "private"."profile_private" to "service_role";

grant delete on table "public"."campfire_guide_resources" to "anon";

grant insert on table "public"."campfire_guide_resources" to "anon";

grant references on table "public"."campfire_guide_resources" to "anon";

grant select on table "public"."campfire_guide_resources" to "anon";

grant trigger on table "public"."campfire_guide_resources" to "anon";

grant truncate on table "public"."campfire_guide_resources" to "anon";

grant update on table "public"."campfire_guide_resources" to "anon";

grant delete on table "public"."campfire_guide_resources" to "authenticated";

grant insert on table "public"."campfire_guide_resources" to "authenticated";

grant references on table "public"."campfire_guide_resources" to "authenticated";

grant select on table "public"."campfire_guide_resources" to "authenticated";

grant trigger on table "public"."campfire_guide_resources" to "authenticated";

grant truncate on table "public"."campfire_guide_resources" to "authenticated";

grant update on table "public"."campfire_guide_resources" to "authenticated";

grant delete on table "public"."campfire_guide_resources" to "postgres";

grant insert on table "public"."campfire_guide_resources" to "postgres";

grant references on table "public"."campfire_guide_resources" to "postgres";

grant select on table "public"."campfire_guide_resources" to "postgres";

grant trigger on table "public"."campfire_guide_resources" to "postgres";

grant truncate on table "public"."campfire_guide_resources" to "postgres";

grant update on table "public"."campfire_guide_resources" to "postgres";

grant delete on table "public"."campfire_guide_resources" to "service_role";

grant insert on table "public"."campfire_guide_resources" to "service_role";

grant references on table "public"."campfire_guide_resources" to "service_role";

grant select on table "public"."campfire_guide_resources" to "service_role";

grant trigger on table "public"."campfire_guide_resources" to "service_role";

grant truncate on table "public"."campfire_guide_resources" to "service_role";

grant update on table "public"."campfire_guide_resources" to "service_role";

grant delete on table "public"."campfire_lanes" to "anon";

grant insert on table "public"."campfire_lanes" to "anon";

grant references on table "public"."campfire_lanes" to "anon";

grant select on table "public"."campfire_lanes" to "anon";

grant trigger on table "public"."campfire_lanes" to "anon";

grant truncate on table "public"."campfire_lanes" to "anon";

grant update on table "public"."campfire_lanes" to "anon";

grant delete on table "public"."campfire_lanes" to "authenticated";

grant insert on table "public"."campfire_lanes" to "authenticated";

grant references on table "public"."campfire_lanes" to "authenticated";

grant select on table "public"."campfire_lanes" to "authenticated";

grant trigger on table "public"."campfire_lanes" to "authenticated";

grant truncate on table "public"."campfire_lanes" to "authenticated";

grant update on table "public"."campfire_lanes" to "authenticated";

grant delete on table "public"."campfire_lanes" to "postgres";

grant insert on table "public"."campfire_lanes" to "postgres";

grant references on table "public"."campfire_lanes" to "postgres";

grant select on table "public"."campfire_lanes" to "postgres";

grant trigger on table "public"."campfire_lanes" to "postgres";

grant truncate on table "public"."campfire_lanes" to "postgres";

grant update on table "public"."campfire_lanes" to "postgres";

grant delete on table "public"."campfire_lanes" to "service_role";

grant insert on table "public"."campfire_lanes" to "service_role";

grant references on table "public"."campfire_lanes" to "service_role";

grant select on table "public"."campfire_lanes" to "service_role";

grant trigger on table "public"."campfire_lanes" to "service_role";

grant truncate on table "public"."campfire_lanes" to "service_role";

grant update on table "public"."campfire_lanes" to "service_role";

grant delete on table "public"."campfire_members" to "anon";

grant insert on table "public"."campfire_members" to "anon";

grant references on table "public"."campfire_members" to "anon";

grant select on table "public"."campfire_members" to "anon";

grant trigger on table "public"."campfire_members" to "anon";

grant truncate on table "public"."campfire_members" to "anon";

grant update on table "public"."campfire_members" to "anon";

grant delete on table "public"."campfire_members" to "authenticated";

grant insert on table "public"."campfire_members" to "authenticated";

grant references on table "public"."campfire_members" to "authenticated";

grant select on table "public"."campfire_members" to "authenticated";

grant trigger on table "public"."campfire_members" to "authenticated";

grant truncate on table "public"."campfire_members" to "authenticated";

grant update on table "public"."campfire_members" to "authenticated";

grant delete on table "public"."campfire_members" to "postgres";

grant insert on table "public"."campfire_members" to "postgres";

grant references on table "public"."campfire_members" to "postgres";

grant select on table "public"."campfire_members" to "postgres";

grant trigger on table "public"."campfire_members" to "postgres";

grant truncate on table "public"."campfire_members" to "postgres";

grant update on table "public"."campfire_members" to "postgres";

grant delete on table "public"."campfire_members" to "service_role";

grant insert on table "public"."campfire_members" to "service_role";

grant references on table "public"."campfire_members" to "service_role";

grant select on table "public"."campfire_members" to "service_role";

grant trigger on table "public"."campfire_members" to "service_role";

grant truncate on table "public"."campfire_members" to "service_role";

grant update on table "public"."campfire_members" to "service_role";

grant delete on table "public"."campfire_realms" to "anon";

grant insert on table "public"."campfire_realms" to "anon";

grant references on table "public"."campfire_realms" to "anon";

grant select on table "public"."campfire_realms" to "anon";

grant trigger on table "public"."campfire_realms" to "anon";

grant truncate on table "public"."campfire_realms" to "anon";

grant update on table "public"."campfire_realms" to "anon";

grant delete on table "public"."campfire_realms" to "authenticated";

grant insert on table "public"."campfire_realms" to "authenticated";

grant references on table "public"."campfire_realms" to "authenticated";

grant select on table "public"."campfire_realms" to "authenticated";

grant trigger on table "public"."campfire_realms" to "authenticated";

grant truncate on table "public"."campfire_realms" to "authenticated";

grant update on table "public"."campfire_realms" to "authenticated";

grant delete on table "public"."campfire_realms" to "postgres";

grant insert on table "public"."campfire_realms" to "postgres";

grant references on table "public"."campfire_realms" to "postgres";

grant select on table "public"."campfire_realms" to "postgres";

grant trigger on table "public"."campfire_realms" to "postgres";

grant truncate on table "public"."campfire_realms" to "postgres";

grant update on table "public"."campfire_realms" to "postgres";

grant delete on table "public"."campfire_realms" to "service_role";

grant insert on table "public"."campfire_realms" to "service_role";

grant references on table "public"."campfire_realms" to "service_role";

grant select on table "public"."campfire_realms" to "service_role";

grant trigger on table "public"."campfire_realms" to "service_role";

grant truncate on table "public"."campfire_realms" to "service_role";

grant update on table "public"."campfire_realms" to "service_role";

grant delete on table "public"."campfire_settings" to "anon";

grant insert on table "public"."campfire_settings" to "anon";

grant references on table "public"."campfire_settings" to "anon";

grant select on table "public"."campfire_settings" to "anon";

grant trigger on table "public"."campfire_settings" to "anon";

grant truncate on table "public"."campfire_settings" to "anon";

grant update on table "public"."campfire_settings" to "anon";

grant delete on table "public"."campfire_settings" to "authenticated";

grant insert on table "public"."campfire_settings" to "authenticated";

grant references on table "public"."campfire_settings" to "authenticated";

grant select on table "public"."campfire_settings" to "authenticated";

grant trigger on table "public"."campfire_settings" to "authenticated";

grant truncate on table "public"."campfire_settings" to "authenticated";

grant update on table "public"."campfire_settings" to "authenticated";

grant delete on table "public"."campfire_settings" to "postgres";

grant insert on table "public"."campfire_settings" to "postgres";

grant references on table "public"."campfire_settings" to "postgres";

grant select on table "public"."campfire_settings" to "postgres";

grant trigger on table "public"."campfire_settings" to "postgres";

grant truncate on table "public"."campfire_settings" to "postgres";

grant update on table "public"."campfire_settings" to "postgres";

grant delete on table "public"."campfire_settings" to "service_role";

grant insert on table "public"."campfire_settings" to "service_role";

grant references on table "public"."campfire_settings" to "service_role";

grant select on table "public"."campfire_settings" to "service_role";

grant trigger on table "public"."campfire_settings" to "service_role";

grant truncate on table "public"."campfire_settings" to "service_role";

grant update on table "public"."campfire_settings" to "service_role";

grant delete on table "public"."campfires" to "anon";

grant insert on table "public"."campfires" to "anon";

grant references on table "public"."campfires" to "anon";

grant select on table "public"."campfires" to "anon";

grant trigger on table "public"."campfires" to "anon";

grant truncate on table "public"."campfires" to "anon";

grant update on table "public"."campfires" to "anon";

grant delete on table "public"."campfires" to "authenticated";

grant insert on table "public"."campfires" to "authenticated";

grant references on table "public"."campfires" to "authenticated";

grant select on table "public"."campfires" to "authenticated";

grant trigger on table "public"."campfires" to "authenticated";

grant truncate on table "public"."campfires" to "authenticated";

grant update on table "public"."campfires" to "authenticated";

grant delete on table "public"."campfires" to "postgres";

grant insert on table "public"."campfires" to "postgres";

grant references on table "public"."campfires" to "postgres";

grant select on table "public"."campfires" to "postgres";

grant trigger on table "public"."campfires" to "postgres";

grant truncate on table "public"."campfires" to "postgres";

grant update on table "public"."campfires" to "postgres";

grant delete on table "public"."campfires" to "service_role";

grant insert on table "public"."campfires" to "service_role";

grant references on table "public"."campfires" to "service_role";

grant select on table "public"."campfires" to "service_role";

grant trigger on table "public"."campfires" to "service_role";

grant truncate on table "public"."campfires" to "service_role";

grant update on table "public"."campfires" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "postgres";

grant insert on table "public"."profiles" to "postgres";

grant references on table "public"."profiles" to "postgres";

grant select on table "public"."profiles" to "postgres";

grant trigger on table "public"."profiles" to "postgres";

grant truncate on table "public"."profiles" to "postgres";

grant update on table "public"."profiles" to "postgres";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."user_preferences" to "anon";

grant insert on table "public"."user_preferences" to "anon";

grant references on table "public"."user_preferences" to "anon";

grant select on table "public"."user_preferences" to "anon";

grant trigger on table "public"."user_preferences" to "anon";

grant truncate on table "public"."user_preferences" to "anon";

grant update on table "public"."user_preferences" to "anon";

grant delete on table "public"."user_preferences" to "authenticated";

grant insert on table "public"."user_preferences" to "authenticated";

grant references on table "public"."user_preferences" to "authenticated";

grant select on table "public"."user_preferences" to "authenticated";

grant trigger on table "public"."user_preferences" to "authenticated";

grant truncate on table "public"."user_preferences" to "authenticated";

grant update on table "public"."user_preferences" to "authenticated";

grant delete on table "public"."user_preferences" to "postgres";

grant insert on table "public"."user_preferences" to "postgres";

grant references on table "public"."user_preferences" to "postgres";

grant select on table "public"."user_preferences" to "postgres";

grant trigger on table "public"."user_preferences" to "postgres";

grant truncate on table "public"."user_preferences" to "postgres";

grant update on table "public"."user_preferences" to "postgres";

grant delete on table "public"."user_preferences" to "service_role";

grant insert on table "public"."user_preferences" to "service_role";

grant references on table "public"."user_preferences" to "service_role";

grant select on table "public"."user_preferences" to "service_role";

grant trigger on table "public"."user_preferences" to "service_role";

grant truncate on table "public"."user_preferences" to "service_role";

grant update on table "public"."user_preferences" to "service_role";


  create policy "profile_private_insert_authenticated"
  on "private"."profile_private"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "profile_private_select_own_authenticated"
  on "private"."profile_private"
  as permissive
  for select
  to authenticated
using ((user_id = ( SELECT auth.uid() AS uid)));



  create policy "profile_private_update_authenticated"
  on "private"."profile_private"
  as permissive
  for update
  to authenticated
using ((user_id = ( SELECT auth.uid() AS uid)))
with check ((user_id = ( SELECT auth.uid() AS uid)));



  create policy "Enable read access for authenticated users"
  on "public"."campfire_lanes"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable read access for authenticated users"
  on "public"."campfire_realms"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for authenticated users"
  on "public"."campfires"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "profiles_insert_authenticated"
  on "public"."profiles"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "profiles_select_authenticated"
  on "public"."profiles"
  as permissive
  for select
  to authenticated
using (true);



  create policy "profiles_update_authenticated"
  on "public"."profiles"
  as permissive
  for update
  to authenticated
using ((id = ( SELECT auth.uid() AS uid)))
with check ((id = ( SELECT auth.uid() AS uid)));



  create policy "user_preferences_insert_authenticated"
  on "public"."user_preferences"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "user_preferences_select_own_authenticated"
  on "public"."user_preferences"
  as permissive
  for select
  to authenticated
using ((user_id = ( SELECT auth.uid() AS uid)));



  create policy "user_preferences_update_authenticated"
  on "public"."user_preferences"
  as permissive
  for update
  to authenticated
using (true)
with check (true);


CREATE TRIGGER trg_profile_private_set_updated_at BEFORE UPDATE ON private.profile_private FOR EACH ROW EXECUTE FUNCTION private.set_updated_at();

CREATE TRIGGER tr_campfire_members_recount AFTER INSERT OR DELETE OR UPDATE OF status ON public.campfire_members FOR EACH ROW EXECUTE FUNCTION public.tr_campfire_members_recount();

CREATE TRIGGER tr_ensure_campfire_settings AFTER INSERT ON public.campfires FOR EACH ROW EXECUTE FUNCTION public.ensure_campfire_settings();

CREATE TRIGGER trg_profiles_set_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION private.set_updated_at();

CREATE TRIGGER trg_user_preferences_set_updated_at BEFORE UPDATE ON public.user_preferences FOR EACH ROW EXECUTE FUNCTION private.set_updated_at();

CREATE TRIGGER trg_provision_user_on_auth_insert AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION private.provision_user_on_auth_insert();



