create extension if not exists "ltree" with schema "public";


  create table "public"."comment_edits" (
    "id" bigint generated by default as identity not null,
    "comment_id" bigint not null,
    "edited_by" uuid not null,
    "edited_at" timestamp with time zone not null default now(),
    "previous_body" text not null
      );


alter table "public"."comment_edits" enable row level security;


  create table "public"."comment_pins" (
    "id" bigint generated by default as identity not null,
    "post_id" uuid not null,
    "comment_id" bigint not null,
    "pin_type" text not null,
    "pinned_by" uuid not null,
    "pinned_at" timestamp with time zone not null default now()
      );


alter table "public"."comment_pins" enable row level security;


  create table "public"."comments" (
    "id" bigint generated by default as identity not null,
    "post_id" uuid not null,
    "campfire_id" uuid,
    "author_id" uuid,
    "parent_comment_id" bigint,
    "thread_path" public.ltree not null,
    "depth" smallint generated always as ((public.nlevel(thread_path) - 1)) stored,
    "body" text not null,
    "author_name_snapshot" text not null,
    "author_avatar_url_snapshot" text,
    "status" text not null default 'active'::text,
    "deleted_at" timestamp with time zone,
    "deleted_by" uuid,
    "hidden_at" timestamp with time zone,
    "hidden_by" uuid,
    "removed_at" timestamp with time zone,
    "removed_by" uuid,
    "moderation_reason" text,
    "is_ai_suggestion" boolean not null default false,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."comments" enable row level security;

CREATE UNIQUE INDEX comment_edits_pkey ON public.comment_edits USING btree (id);

CREATE UNIQUE INDEX comment_pins_one_per_type_per_post ON public.comment_pins USING btree (post_id, pin_type);

CREATE UNIQUE INDEX comment_pins_one_row_per_comment ON public.comment_pins USING btree (comment_id);

CREATE UNIQUE INDEX comment_pins_pkey ON public.comment_pins USING btree (id);

CREATE UNIQUE INDEX comments_pkey ON public.comments USING btree (id);

CREATE INDEX idx_comment_edits_comment_id ON public.comment_edits USING btree (comment_id, edited_at DESC);

CREATE INDEX idx_comment_pins_post ON public.comment_pins USING btree (post_id);

CREATE INDEX idx_comments_author_id ON public.comments USING btree (author_id);

CREATE INDEX idx_comments_post_active_created_at ON public.comments USING btree (post_id, created_at DESC) WHERE (status = 'active'::text);

CREATE INDEX idx_comments_post_created_at ON public.comments USING btree (post_id, created_at DESC);

CREATE INDEX idx_comments_post_parent ON public.comments USING btree (post_id, parent_comment_id);

CREATE INDEX idx_comments_thread_path_gist ON public.comments USING gist (thread_path);

CREATE UNIQUE INDEX ux_comments_thread_path ON public.comments USING btree (thread_path);

alter table "public"."comment_edits" add constraint "comment_edits_pkey" PRIMARY KEY using index "comment_edits_pkey";

alter table "public"."comment_pins" add constraint "comment_pins_pkey" PRIMARY KEY using index "comment_pins_pkey";

alter table "public"."comments" add constraint "comments_pkey" PRIMARY KEY using index "comments_pkey";

alter table "public"."comment_edits" add constraint "comment_edits_comment_id_fkey" FOREIGN KEY (comment_id) REFERENCES public.comments(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."comment_edits" validate constraint "comment_edits_comment_id_fkey";

alter table "public"."comment_edits" add constraint "comment_edits_edited_by_fkey" FOREIGN KEY (edited_by) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."comment_edits" validate constraint "comment_edits_edited_by_fkey";

alter table "public"."comment_pins" add constraint "comment_pin_type_check" CHECK ((pin_type = ANY (ARRAY['author'::text, 'professional'::text, 'moderator'::text]))) not valid;

alter table "public"."comment_pins" validate constraint "comment_pin_type_check";

alter table "public"."comment_pins" add constraint "comment_pins_comment_id_fkey" FOREIGN KEY (comment_id) REFERENCES public.comments(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."comment_pins" validate constraint "comment_pins_comment_id_fkey";

alter table "public"."comment_pins" add constraint "comment_pins_one_per_type_per_post" UNIQUE using index "comment_pins_one_per_type_per_post";

alter table "public"."comment_pins" add constraint "comment_pins_one_row_per_comment" UNIQUE using index "comment_pins_one_row_per_comment";

alter table "public"."comment_pins" add constraint "comment_pins_pinned_by_fkey" FOREIGN KEY (pinned_by) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."comment_pins" validate constraint "comment_pins_pinned_by_fkey";

alter table "public"."comment_pins" add constraint "comment_pins_post_id_fkey" FOREIGN KEY (post_id) REFERENCES public.posts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."comment_pins" validate constraint "comment_pins_post_id_fkey";

alter table "public"."comments" add constraint "comment_status_check" CHECK ((status = ANY (ARRAY['active'::text, 'deleted'::text, 'hidden'::text, 'removed'::text]))) not valid;

alter table "public"."comments" validate constraint "comment_status_check";

alter table "public"."comments" add constraint "comments_author_id_fkey" FOREIGN KEY (author_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."comments" validate constraint "comments_author_id_fkey";

alter table "public"."comments" add constraint "comments_campfire_id_fkey" FOREIGN KEY (campfire_id) REFERENCES public.campfires(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."comments" validate constraint "comments_campfire_id_fkey";

alter table "public"."comments" add constraint "comments_deleted_by_fkey" FOREIGN KEY (deleted_by) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."comments" validate constraint "comments_deleted_by_fkey";

alter table "public"."comments" add constraint "comments_depth_max_check" CHECK ((depth <= 6)) not valid;

alter table "public"."comments" validate constraint "comments_depth_max_check";

alter table "public"."comments" add constraint "comments_hidden_by_fkey" FOREIGN KEY (hidden_by) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."comments" validate constraint "comments_hidden_by_fkey";

alter table "public"."comments" add constraint "comments_parent_comment_id_fkey" FOREIGN KEY (parent_comment_id) REFERENCES public.comments(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."comments" validate constraint "comments_parent_comment_id_fkey";

alter table "public"."comments" add constraint "comments_post_id_fkey" FOREIGN KEY (post_id) REFERENCES public.posts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."comments" validate constraint "comments_post_id_fkey";

alter table "public"."comments" add constraint "comments_removed_by_fkey" FOREIGN KEY (removed_by) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."comments" validate constraint "comments_removed_by_fkey";

alter table "public"."comments" add constraint "comments_root_parent_check" CHECK ((((parent_comment_id IS NULL) AND (depth = 0)) OR ((parent_comment_id IS NOT NULL) AND (depth >= 1)))) not valid;

alter table "public"."comments" validate constraint "comments_root_parent_check";

alter table "public"."comments" add constraint "comments_thread_path_len_check" CHECK ((public.nlevel(thread_path) <= 6)) not valid;

alter table "public"."comments" validate constraint "comments_thread_path_len_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION private.provision_user_on_auth_insert()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_username text;
  v_is_anonymous boolean;
begin
  -- username may be provided at signup; if not present, keep null
  v_username := nullif(new.raw_user_meta_data->>'username', '');

  -- infer anonymous sign-in from auth metadata (avoid relying on nonstandard columns)
  -- note: this is a best-effort inference and remains a display/state flag only.
  v_is_anonymous :=
    coalesce((new.is_anonymous) = 'true', false);

  -- public profile card
  insert into public.profiles (
    id,
    username,
    avatar_url,
    is_anonymous
  )
  values (
    new.id,
    v_username,
    'default_profile.png',
    v_is_anonymous
  )
  on conflict (id) do nothing;

  -- sensitive private row (minimal defaults; email optional)
  insert into private.profile_private (
    user_id,
    email
  )
  values (
    new.id,
    nullif(new.email, '')
  )
  on conflict (user_id) do nothing;

  -- preferences row (defaults)
  insert into public.user_preferences (
    user_id
  )
  values (
    new.id
  )
  on conflict (user_id) do nothing;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION private.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  new.updated_at := now();
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.ensure_campfire_settings()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.campfire_settings (campfire_id)
  values (new.id)
  on conflict (campfire_id) do nothing;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.recount_campfire_members(p_campfire_id uuid)
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
  update public.campfires c
  set member_count = (
    select count(*)
    from public.campfire_members m
    where m.campfire_id = c.id
      and m.status = 'approved'
  ),
  updated_at = now()
  where c.id = p_campfire_id;
$function$
;

CREATE OR REPLACE FUNCTION public.tr_campfire_members_recount()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_campfire_id uuid;
begin
  v_campfire_id := coalesce(new.campfire_id, old.campfire_id);

  -- only recompute when insert/delete, or when status changes
  if (tg_op = 'UPDATE') then
    if new.status is not distinct from old.status then
      return new;
    end if;
  end if;

  perform public.recount_campfire_members(v_campfire_id);
  return coalesce(new, old);
end;
$function$
;

grant delete on table "public"."campfire_guide_resources" to "postgres";

grant insert on table "public"."campfire_guide_resources" to "postgres";

grant references on table "public"."campfire_guide_resources" to "postgres";

grant select on table "public"."campfire_guide_resources" to "postgres";

grant trigger on table "public"."campfire_guide_resources" to "postgres";

grant truncate on table "public"."campfire_guide_resources" to "postgres";

grant update on table "public"."campfire_guide_resources" to "postgres";

grant delete on table "public"."campfire_lanes" to "postgres";

grant insert on table "public"."campfire_lanes" to "postgres";

grant references on table "public"."campfire_lanes" to "postgres";

grant select on table "public"."campfire_lanes" to "postgres";

grant trigger on table "public"."campfire_lanes" to "postgres";

grant truncate on table "public"."campfire_lanes" to "postgres";

grant update on table "public"."campfire_lanes" to "postgres";

grant delete on table "public"."campfire_members" to "postgres";

grant insert on table "public"."campfire_members" to "postgres";

grant references on table "public"."campfire_members" to "postgres";

grant select on table "public"."campfire_members" to "postgres";

grant trigger on table "public"."campfire_members" to "postgres";

grant truncate on table "public"."campfire_members" to "postgres";

grant update on table "public"."campfire_members" to "postgres";

grant delete on table "public"."campfire_realms" to "postgres";

grant insert on table "public"."campfire_realms" to "postgres";

grant references on table "public"."campfire_realms" to "postgres";

grant select on table "public"."campfire_realms" to "postgres";

grant trigger on table "public"."campfire_realms" to "postgres";

grant truncate on table "public"."campfire_realms" to "postgres";

grant update on table "public"."campfire_realms" to "postgres";

grant delete on table "public"."campfire_settings" to "postgres";

grant insert on table "public"."campfire_settings" to "postgres";

grant references on table "public"."campfire_settings" to "postgres";

grant select on table "public"."campfire_settings" to "postgres";

grant trigger on table "public"."campfire_settings" to "postgres";

grant truncate on table "public"."campfire_settings" to "postgres";

grant update on table "public"."campfire_settings" to "postgres";

grant delete on table "public"."campfires" to "postgres";

grant insert on table "public"."campfires" to "postgres";

grant references on table "public"."campfires" to "postgres";

grant select on table "public"."campfires" to "postgres";

grant trigger on table "public"."campfires" to "postgres";

grant truncate on table "public"."campfires" to "postgres";

grant update on table "public"."campfires" to "postgres";

grant delete on table "public"."collection_items" to "postgres";

grant insert on table "public"."collection_items" to "postgres";

grant references on table "public"."collection_items" to "postgres";

grant select on table "public"."collection_items" to "postgres";

grant trigger on table "public"."collection_items" to "postgres";

grant truncate on table "public"."collection_items" to "postgres";

grant update on table "public"."collection_items" to "postgres";

grant delete on table "public"."collections" to "postgres";

grant insert on table "public"."collections" to "postgres";

grant references on table "public"."collections" to "postgres";

grant select on table "public"."collections" to "postgres";

grant trigger on table "public"."collections" to "postgres";

grant truncate on table "public"."collections" to "postgres";

grant update on table "public"."collections" to "postgres";

grant delete on table "public"."comment_edits" to "anon";

grant insert on table "public"."comment_edits" to "anon";

grant references on table "public"."comment_edits" to "anon";

grant select on table "public"."comment_edits" to "anon";

grant trigger on table "public"."comment_edits" to "anon";

grant truncate on table "public"."comment_edits" to "anon";

grant update on table "public"."comment_edits" to "anon";

grant delete on table "public"."comment_edits" to "authenticated";

grant insert on table "public"."comment_edits" to "authenticated";

grant references on table "public"."comment_edits" to "authenticated";

grant select on table "public"."comment_edits" to "authenticated";

grant trigger on table "public"."comment_edits" to "authenticated";

grant truncate on table "public"."comment_edits" to "authenticated";

grant update on table "public"."comment_edits" to "authenticated";

grant delete on table "public"."comment_edits" to "postgres";

grant insert on table "public"."comment_edits" to "postgres";

grant references on table "public"."comment_edits" to "postgres";

grant select on table "public"."comment_edits" to "postgres";

grant trigger on table "public"."comment_edits" to "postgres";

grant truncate on table "public"."comment_edits" to "postgres";

grant update on table "public"."comment_edits" to "postgres";

grant delete on table "public"."comment_edits" to "service_role";

grant insert on table "public"."comment_edits" to "service_role";

grant references on table "public"."comment_edits" to "service_role";

grant select on table "public"."comment_edits" to "service_role";

grant trigger on table "public"."comment_edits" to "service_role";

grant truncate on table "public"."comment_edits" to "service_role";

grant update on table "public"."comment_edits" to "service_role";

grant delete on table "public"."comment_pins" to "anon";

grant insert on table "public"."comment_pins" to "anon";

grant references on table "public"."comment_pins" to "anon";

grant select on table "public"."comment_pins" to "anon";

grant trigger on table "public"."comment_pins" to "anon";

grant truncate on table "public"."comment_pins" to "anon";

grant update on table "public"."comment_pins" to "anon";

grant delete on table "public"."comment_pins" to "authenticated";

grant insert on table "public"."comment_pins" to "authenticated";

grant references on table "public"."comment_pins" to "authenticated";

grant select on table "public"."comment_pins" to "authenticated";

grant trigger on table "public"."comment_pins" to "authenticated";

grant truncate on table "public"."comment_pins" to "authenticated";

grant update on table "public"."comment_pins" to "authenticated";

grant delete on table "public"."comment_pins" to "postgres";

grant insert on table "public"."comment_pins" to "postgres";

grant references on table "public"."comment_pins" to "postgres";

grant select on table "public"."comment_pins" to "postgres";

grant trigger on table "public"."comment_pins" to "postgres";

grant truncate on table "public"."comment_pins" to "postgres";

grant update on table "public"."comment_pins" to "postgres";

grant delete on table "public"."comment_pins" to "service_role";

grant insert on table "public"."comment_pins" to "service_role";

grant references on table "public"."comment_pins" to "service_role";

grant select on table "public"."comment_pins" to "service_role";

grant trigger on table "public"."comment_pins" to "service_role";

grant truncate on table "public"."comment_pins" to "service_role";

grant update on table "public"."comment_pins" to "service_role";

grant delete on table "public"."comments" to "anon";

grant insert on table "public"."comments" to "anon";

grant references on table "public"."comments" to "anon";

grant select on table "public"."comments" to "anon";

grant trigger on table "public"."comments" to "anon";

grant truncate on table "public"."comments" to "anon";

grant update on table "public"."comments" to "anon";

grant delete on table "public"."comments" to "authenticated";

grant insert on table "public"."comments" to "authenticated";

grant references on table "public"."comments" to "authenticated";

grant select on table "public"."comments" to "authenticated";

grant trigger on table "public"."comments" to "authenticated";

grant truncate on table "public"."comments" to "authenticated";

grant update on table "public"."comments" to "authenticated";

grant delete on table "public"."comments" to "postgres";

grant insert on table "public"."comments" to "postgres";

grant references on table "public"."comments" to "postgres";

grant select on table "public"."comments" to "postgres";

grant trigger on table "public"."comments" to "postgres";

grant truncate on table "public"."comments" to "postgres";

grant update on table "public"."comments" to "postgres";

grant delete on table "public"."comments" to "service_role";

grant insert on table "public"."comments" to "service_role";

grant references on table "public"."comments" to "service_role";

grant select on table "public"."comments" to "service_role";

grant trigger on table "public"."comments" to "service_role";

grant truncate on table "public"."comments" to "service_role";

grant update on table "public"."comments" to "service_role";

grant delete on table "public"."health_tip_categories" to "postgres";

grant insert on table "public"."health_tip_categories" to "postgres";

grant references on table "public"."health_tip_categories" to "postgres";

grant select on table "public"."health_tip_categories" to "postgres";

grant trigger on table "public"."health_tip_categories" to "postgres";

grant truncate on table "public"."health_tip_categories" to "postgres";

grant update on table "public"."health_tip_categories" to "postgres";

grant delete on table "public"."health_tip_sources" to "postgres";

grant insert on table "public"."health_tip_sources" to "postgres";

grant references on table "public"."health_tip_sources" to "postgres";

grant select on table "public"."health_tip_sources" to "postgres";

grant trigger on table "public"."health_tip_sources" to "postgres";

grant truncate on table "public"."health_tip_sources" to "postgres";

grant update on table "public"."health_tip_sources" to "postgres";

grant delete on table "public"."health_tips" to "postgres";

grant insert on table "public"."health_tips" to "postgres";

grant references on table "public"."health_tips" to "postgres";

grant select on table "public"."health_tips" to "postgres";

grant trigger on table "public"."health_tips" to "postgres";

grant truncate on table "public"."health_tips" to "postgres";

grant update on table "public"."health_tips" to "postgres";

grant delete on table "public"."post_media" to "postgres";

grant insert on table "public"."post_media" to "postgres";

grant references on table "public"."post_media" to "postgres";

grant select on table "public"."post_media" to "postgres";

grant trigger on table "public"."post_media" to "postgres";

grant truncate on table "public"."post_media" to "postgres";

grant update on table "public"."post_media" to "postgres";

grant delete on table "public"."post_slides" to "postgres";

grant insert on table "public"."post_slides" to "postgres";

grant references on table "public"."post_slides" to "postgres";

grant select on table "public"."post_slides" to "postgres";

grant trigger on table "public"."post_slides" to "postgres";

grant truncate on table "public"."post_slides" to "postgres";

grant update on table "public"."post_slides" to "postgres";

grant delete on table "public"."post_tags" to "postgres";

grant insert on table "public"."post_tags" to "postgres";

grant references on table "public"."post_tags" to "postgres";

grant select on table "public"."post_tags" to "postgres";

grant trigger on table "public"."post_tags" to "postgres";

grant truncate on table "public"."post_tags" to "postgres";

grant update on table "public"."post_tags" to "postgres";

grant delete on table "public"."post_views" to "postgres";

grant insert on table "public"."post_views" to "postgres";

grant references on table "public"."post_views" to "postgres";

grant select on table "public"."post_views" to "postgres";

grant trigger on table "public"."post_views" to "postgres";

grant truncate on table "public"."post_views" to "postgres";

grant update on table "public"."post_views" to "postgres";

grant delete on table "public"."post_votes" to "postgres";

grant insert on table "public"."post_votes" to "postgres";

grant references on table "public"."post_votes" to "postgres";

grant select on table "public"."post_votes" to "postgres";

grant trigger on table "public"."post_votes" to "postgres";

grant truncate on table "public"."post_votes" to "postgres";

grant update on table "public"."post_votes" to "postgres";

grant delete on table "public"."posts" to "postgres";

grant insert on table "public"."posts" to "postgres";

grant references on table "public"."posts" to "postgres";

grant select on table "public"."posts" to "postgres";

grant trigger on table "public"."posts" to "postgres";

grant truncate on table "public"."posts" to "postgres";

grant update on table "public"."posts" to "postgres";

grant delete on table "public"."profiles" to "postgres";

grant insert on table "public"."profiles" to "postgres";

grant references on table "public"."profiles" to "postgres";

grant select on table "public"."profiles" to "postgres";

grant trigger on table "public"."profiles" to "postgres";

grant truncate on table "public"."profiles" to "postgres";

grant update on table "public"."profiles" to "postgres";

grant delete on table "public"."tags" to "postgres";

grant insert on table "public"."tags" to "postgres";

grant references on table "public"."tags" to "postgres";

grant select on table "public"."tags" to "postgres";

grant trigger on table "public"."tags" to "postgres";

grant truncate on table "public"."tags" to "postgres";

grant update on table "public"."tags" to "postgres";

grant delete on table "public"."user_preferences" to "postgres";

grant insert on table "public"."user_preferences" to "postgres";

grant references on table "public"."user_preferences" to "postgres";

grant select on table "public"."user_preferences" to "postgres";

grant trigger on table "public"."user_preferences" to "postgres";

grant truncate on table "public"."user_preferences" to "postgres";

grant update on table "public"."user_preferences" to "postgres";


  create policy "comment_pins_select_authenticated"
  on "public"."comment_pins"
  as permissive
  for select
  to authenticated
using (true);



  create policy "comments_select_authenticated"
  on "public"."comments"
  as permissive
  for select
  to authenticated
using (true);


CREATE TRIGGER tr_comments_set_updated_at BEFORE UPDATE ON public.comments FOR EACH ROW EXECUTE FUNCTION private.set_updated_at();



